services:
  exercise_pg:
    container_name: exercise_pg
    image: postgres:latest
    restart: always
    env_file:
      - docker.env
    ports:
      - "5436:5432"

  exercise_redis:
    container_name: exercise_redis
    image: redis:alpine
    env_file:
      - docker.env
    ports:
      - '6381:6379'
